{ stdenv, rustc, pahole, lib, version }:

with lib.kernel;

/*
  Those are values that are depending on Nixpkgs inputs, e.g. tool versions.
  The current state is FOR EVALUATION PURPOSES ONLY!

  A few notes on that:

  * We'll probably need a Matrix for kconfig of (arch x version x toolchain)
    generated by `rokc maintainer`
  * Toolchain implies a stdenv + a rust compiler. ROKC automatically enters a
    nix-shell with those tools inside and derives information from it.
  * It might have cases where this requires an override. For these cases,
    this file exists. Most likely, most of these values in here aren't being
    generated by Nix code.
 */

lib.mkMerge [
  {
    PAHOLE_VERSION = freeform (toString (lib.toInt (builtins.replaceStrings ["."] [""] pahole.version)));
    CC_VERSION_TEXT = freeform "gcc (GCC) 15.2.0";
    CC_IS_GCC = yes;
    CLANG_VERSION = freeform "0";
    GCC_VERSION = freeform "150200";
    LD_VERSION = freeform "24400";
    AS_IS_GNU = yes;
    LD_IS_BFD = yes;
    LLD_VERSION = freeform "0";
  }
  (lib.mkIf (lib.versionAtLeast version "6.12") {
    RUST_IS_AVAILABLE = yes;
    RUSTC_VERSION = freeform "109200";
    RUSTC_LLVM_VERSION = freeform "210108";
  })
]
